apiVersion: kagent.dev/v1alpha2
kind: ModelConfig
metadata:
  name: ollama-config
  namespace: kagent
spec:
  provider: Ollama
  model: qwen2.5:7b
  apiKeySecret: kagent-ollama
  apiKeySecretKey: OPENAI_API_KEY
  ollama:
    host: http://172.17.0.1:11434